Revert "qcacmn: Fetch rssi from radar report pulse"
../drivers/staging/qcacld-3.0/../qca-wifi-host-cmn/umac/dfs/core/src/filtering/dfs_phyerr_tlv.c:165:17: error: array index 3 is past the end of the array (that has type 'uint32_t[3]' (aka 'unsigned int[3]')) [-Werror,-Warray-bounds]
  165 |         rsu->rssi = MS(rs[RADAR_REPORT_PULSE_REG_4], RADAR_REPORT_PULSE_RSSI);
      |                        ^  ~~~~~~~~~~~~~~~~~~~~~~~~
../drivers/staging/qcacld-3.0/../qca-wifi-host-cmn/umac/dfs/core/src/filtering/../dfs_phyerr_tlv.h:30:23: note: expanded from macro 'MS'
   30 | #define MS(_v, _f) (((_v) & _f) >> _f##_S)
      |                       ^~
../drivers/staging/qcacld-3.0/../qca-wifi-host-cmn/umac/dfs/core/src/filtering/dfs_phyerr_tlv.c:123:2: note: array 'rs' declared here
  123 |         uint32_t rs[3];
      |         ^
1 error generated.
This reverts commit 7e12194279e0012d474c7a14a30a6bbf7d0c1caf.

Signed-off-by: Diaz1401 <diaznura@outlook.com>